class Locators:
    l_username='//*[@id="username"]'
    l_pwd='//*[@id="password"]'
    l_submit='//*[@id="submit"]'
    l_configure='//*[@id="container"]/button/div[3]/div/div[2]/button/ux-icon'
    l_external_host='//*[@id="external-access-host-id-input"]'
    l_registry='//*[@id="docker-registry-id-input"]'
    l_orgename='//*[@id="docker-orgname-id-input"]'
    l_deploysize='//*[@id="apphub-deploySize-id"]/div[3]/div/ux-radio-button/label/span'
    l_k8s='//*[@id="k8s-provider-id"]/div[1]/div/ux-radio-button/label/span'
    l_capability='//*[@id="ux-wizard-0-step-1-label"]'
    l_security='//*[@id="ux-wizard-0-step-2-label"]'
    l_userpwd='//*[@id="opsbridge-admin-password-id-input"]'
    l_confirnuserpwd='//*[@id="opsbridge-admin-password-id-confirm-input"]'
    cert_upload="//label[text()=' Click here or Drag and Drop to add files ' and @for='trusted-ca-list-id']"
    js_viewbrowser="document.getElementById('trusted-ca-list-id').classList.remove('sr-only')"
    browser_ele='//*[@id="trusted-ca-list-id"]'
    cert_verify='/html/body/app-root/div/deployments/div/div/deploy-config-dialog/div/div/app-deploy-form/form/div/ux-marquee-wizard/div[2]/div[1]/ux-marquee-wizard-step[3]/div[2]/div[3]/div/param-group/div/div/div/group-type/div/certificate-authority-type/div/button'
    database_section='//*[@id="ux-wizard-0-step-3-label"]'
    db_host='//*[@id="persistence-db-host-id-input"]'
    db_port='//*[@id="persistence-db-port-id-input"]'
    auto_create='/html/body/app-root/div/deployments/div/div/deploy-config-dialog/div/div/app-deploy-form/form/div/ux-marquee-wizard/div[2]/div[1]/ux-marquee-wizard-step[4]/div[2]/div[2]/div/param-group/div/div/div[9]/params-parameter/div/param-boolean-type/div/ux-toggleswitch/label/div/div[2]'
    postgres_admin='//*[@id="dbadmin-user-id-input"]'
    postgres_admin_pwd='//*[@id="dbadmin-pass-id-input"]'
    postgres_dbadmin='//*[@id="dbadmin-dbname-id-input"]'
    postgres_verify='/html/body/app-root/div/deployments/div/div/deploy-config-dialog/div/div/app-deploy-form/form/div/ux-marquee-wizard/div[2]/div[1]/ux-marquee-wizard-step[4]/div[2]/div[3]/div/param-group/div/div/div/group-type/div/database-type/div/button'
    idm_pwd='//*[@id="persistence-db-pass-autocreate-id-input"]'
    idm_confirm='//*[@id="persistence-db-pass-autocreate-id-confirm-input"]'
    bvd_pwd='//*[@id="persistence-db-pass-bvd-autocreate-id-input"]'
    bvd_confirm='//*[@id="persistence-db-pass-bvd-autocreate-id-confirm-input"]'
    apls='//*[@id="persistence-db-pass-apls-autocreate-id-input"]'
    apls_confirm='//*[@id="persistence-db-pass-apls-autocreate-id-confirm-input"]'
    monitoring_admin='//*[@id="persistence-db-pass-monitoringadmin-autocreate-id-input"]'
    monitoring_admin_confirm='//*[@id="persistence-db-pass-monitoringadmin-autocreate-id-confirm-input"]'
    credential_mang='//*[@id="persistence-db-pass-credmanager-autocreate-id-input"]'
    credential_mang_confirm='//*[@id="persistence-db-pass-credmanager-autocreate-id-confirm-input"]'
    aec='//*[@id="persistence-db-pass-aec-autocreate-id-input"]'
    aec_confirm='//*[@id="persistence-db-pass-aec-autocreate-id-confirm-input"]'
    monitoring_snf='//*[@id="persistence-db-pass-monitoringsnf-autocreate-id-input"]'
    monitoring_snf_confirm='//*[@id="persistence-db-pass-monitoringsnf-autocreate-id-confirm-input"]'
    external_vertica='/html/body/app-root/div/deployments/div/div/deploy-config-dialog/div/div/app-deploy-form/form/div/ux-marquee-wizard/div[2]/div[1]/ux-marquee-wizard-step[4]/div[2]/div[27]/div/param-group/div/div/div[1]/params-parameter/div/span/param-option-type-radio/div/div/div[1]/div/ux-radio-button/label/span'
    vertica_host='//*[@id="vertica-host-id-input"]'
    vertica_bd='//*[@id="vertica-db-name-id-input"]'
    rw_pwd='//*[@id="vertica-rw-user-password-id-input"]'
    rw_verify='(//button[@type=\'button\' and contains(@class,\'m-b btn-icon-with-text btn button-primary verify-button\')])[12]'
    ro_pwd='//*[@id="vertica-ro-user-password-id-input"]'
    ro_verify='/html/body/app-root/div/deployments/div/div/deploy-config-dialog/div/div/app-deploy-form/form/div/ux-marquee-wizard/div[2]/div[1]/ux-marquee-wizard-step[4]/div[2]/div[27]/div/param-group/div/div/div/group-type/div/database-type/div/button'
    advanced_page='//*[@id="ux-wizard-0-step-4-label"]'
    storage_class1='//*[@id="default-storageClass-id-input"]'
    # storage_class2='//*[@id="cloud-default-rwo-storageClass-id-input"]'
    deploy='/html/body/app-root/div/deployments/div/div/deploy-config-dialog/div/div/app-deploy-form/form/div/ux-marquee-wizard/div[2]/div[2]/button[2]'
    show_advance='//a[text()=\'Show advanced\']'
    deploy_now='/html/body/ngb-modal-window[2]/div/div/app-image-missing/div[2]/div/button'
    deployment_name='//*[@id="deploy-confirm-name-input"]'
    create_ns='/html/body/ngb-modal-window[2]/div/div/deploy-confirm-dialog/div/form/div[3]/ux-radio-button[2]/label/span'
    ns='//*[@id="dep-confirm-namespace-input"]'
    check_box='/html/body/ngb-modal-window[2]/div/div/deploy-confirm-dialog/div/form/div[6]/ux-checkbox/label/div'
    final_deploy='/html/body/ngb-modal-window[2]/div/div/deploy-confirm-dialog/div/form/div[8]/button[1]'